/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  ug1Sidebar: [
    {
      type: 'category',
      label: 'Underground',
      link: {
          type: 'generated-index',
          slug: '/ug1'
        },
      items: [
        'ug1/setup',
        'ug1/info',
        'ug1/underground',
      ],
    },
    {
      type: 'link',
      label: 'Speedrun.com',
      href: 'https://www.speedrun.com/nfsu',
    },
    {
      type: 'link',
      label: 'NFS.onl',
      href: 'https://nfs.onl',
    },
  ],
  mw05Sidebar: [
    {
      type: 'category',
      label: 'Most Wanted (2005)',
      link: {
          type: 'generated-index',
          slug: '/mw05'
        },
      items: [
        'mw05/setup',
        'mw05/info',
        'mw05/simple-any',
        'mw05/inter-any',
        'mw05/info2',
        'mw05/expert-any',
      ],
    },
    {
      type: 'link',
      label: 'Speedrun.com',
      href: 'https://www.speedrun.com/nfsmw05',
    },
    {
      type: 'link',
      label: 'Category Extensions',
      href: 'https://www.speedrun.com/nfsmw05_ce',
    },
    {
      type: 'link',
      label: 'NFSMWRANKED',
      href: 'https://nfsmwrank2005.rf.gd/ranked-driver/',
    },
    {
      type: 'link',
      label: 'Extreme Most Wanted Racers',
      href: 'https://extrememostwantedracers.weebly.com/',
    },
  ],
  carbonSidebar: [
    {
      type: 'category',
      label: 'Carbon',
      link: {
          type: 'generated-index',
          slug: '/carbon'
        },
      items: [
        'carbon/setup',
        'carbon/info',
        'carbon/ng-any',
        'carbon/ngp-any',
      ],
    },
    {
      type: 'link',
      label: 'Speedrun.com',
      href: 'https://www.speedrun.com/nfsc',
    },
    {
      type: 'link',
      label: 'Category Extensions',
      href: 'https://www.speedrun.com/nfscce',
    },
  ],
  shiftSidebar: [
    {
      type: 'category',
      label: 'Shift',
      link: {
          type: 'generated-index',
          slug: '/shift'
        },
      items: [
        'shift/info',
        'shift/simple-any',
        'shift/exp-any',
        'shift/pro-any',
        'shift/tier-any',
        'shift/tier-100',
        'shift/tuning',
        ],
    },
    {
      type: 'link',
      label: 'Speedrun.com',
      href: 'https://www.speedrun.com/nfsshift',
    },
  ],
  shift2Sidebar: [
    {
      type: 'category',
      label: 'Shift 2: Unleashed',
      link: {
          type: 'generated-index',
          slug: '/shift2'
        },
      items: [
        'shift2/info',
        'shift2/any',
        'shift2/tuning',
        ],
    },
    {
      type: 'link',
      label: 'Speedrun.com',
      href: 'https://www.speedrun.com/nfsshift2',
    },
  ],
};

export default sidebars;
